# Generated by Django 4.2.6 on 2023-11-06 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JOBS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(max_length=255)),
                ('appliedAt', models.DateField(auto_now_add=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliedJob', to='JOBS.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliedUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
