# Generated by Django 4.2.6 on 2023-12-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBS', '0003_alter_job_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'Phd')], default='Bachelors', max_length=10),
        ),
    ]
